feat: edit & delete link
Eirbware/cassis pull request #3
Opened 2024-07-22 22:36 UTC by Catatomik

2024-07-22 22:38 UTC, Catatomik commented
⚠️ Design still needs to be done
➕ Various fixes/improvement (typing, data validation...) => need to be pushed even harder

2024-07-22 22:52 UTC, Catatomik commented on server/api/remove.post.ts
> +    const del = await LinkShema.deleteOne({ uid: body.uid })
Need one more filter : `createdBy: user.user`

2024-07-23 08:07 UTC, NemoDacremont commented
Vu que c'est toi je vais râler :p

Y'a trop de modifications dans la PR, elle devrait être découpée en 3 : une edit, une delete, et une refactor

2024-07-23 08:12 UTC, NemoDacremont requested changes
mauvaise indentation et double log

2024-07-23 08:30 UTC, Catatomik commented
> Vu que c'est toi je vais râler :p
> 
> Y'a trop de modifications dans la PR, elle devrait être découpée en 3 : une edit, une delete, et une refactor

Effectivement c'est le bazar, et c'est par soucis d'efficacité (et un peu de flemmardise) que j'en n'ai fait qu'une.
Si j'avais dû découper, j'aurais au moins fait "refactor" et "edit & remove", mais dans ce cas, il aurait fallut attendre que la PR "refactor" soit acceptée pour se baser dessus et écrire "edit & remove" (qui nécessitait le refactor).
C'était donc plus simple mais moins propre...

2024-07-23 08:37 UTC, Catatomik commented
> mauvaise indentation et double log

L'indentation est due au formatage (et donc devrait être dans un autre commit, mais détailler à l'intérieur des lignes ?...)
Double log c'est aussi une erreur de commit, ça devrait être avec mais ça a été retiré dans un commit de formatage...

Ce qui m'a rendu la tâche plus compliquée, c'est aussi que les fichiers commit n'étaient *pas initialement* formatés.
Cela a donc modifié du code existant à une multitude d'emplacements, rendant la séparation en commits plus complexe...

2024-07-24 13:05 UTC, Catatomik commented
Opening more precise PRs, see #4.

2024-07-24 13:05 UTC, closed without merging