feat(project): edit link
Eirbware/cassis pull request #6
Opened 2024-07-24 16:58 UTC by Catatomik

2024-07-24 17:34 UTC, NemoDacremont requested changes

2024-07-24 17:34 UTC, NemoDacremont commented on components/LinkCard.vue
Je te fais confiance pour l'affichage pour l'instant, si besoin, ça sera modifié plus tard de toute façon

2024-07-24 17:34 UTC, NemoDacremont commented on server/api/edit.post.ts
> +    if (!isBodyWithProps(body, ['uid'] as const)) {
C'est normal que la fonction soit pas importée ?

2024-07-24 17:34 UTC, NemoDacremont commented on server/api/edit.post.ts
> +      status: 'success',
`statusCode: 200` plutôt

2024-07-24 17:34 UTC, NemoDacremont commented on server/api/edit.post.ts
> +  try {
Je pense que le `try..catch` est superflu, des return ne nuiraient pas à la lisibilité et raccourciraient le code, en rendant sa lecture plus linéaire

2024-07-24 18:32 UTC, Catatomik commented on server/api/edit.post.ts
> +      status: 'success',
Il faudrait aussi changer avec `new.post.ts`, c'était purement par consistance

2024-07-24 18:32 UTC, Catatomik commented on server/api/edit.post.ts
> +  try {
Encore une fois, j'ai recopié la structure de `new.post.ts`, mais je suis d'accord.
Il faudra aussi le changer :)

2024-07-24 18:37 UTC, Catatomik commented on server/api/edit.post.ts
> +    if (!isBodyWithProps(body, ['uid'] as const)) {
Elle est définie sous [`server/utils`](https://nuxt.com/docs/guide/directory-structure/server#server-utilities), ce qui semble être automatiquement importé à la compilation

2024-07-24 18:37 UTC, Catatomik commented on components/LinkCard.vue
Il y en aura vivement besoin, là c'est uniquement fonctionnel

2024-07-24 18:44 UTC, Catatomik commented on server/api/edit.post.ts
> +    if (!isBodyWithProps(body, ['uid'] as const)) {
Ajouté pour la clarté, voir https://github.com/Eirbware/cassis/pull/6/commits/edfa8a0b3f4563da5cd31c9521aad44783c937cb

2024-07-25 15:48 UTC, NemoDacremont commented on server/api/edit.post.ts
> +    if (isBodyWithProps(body, ['url'] as const) && typeof body.url === 'string') link.url = body.url
formatURL est inutilisée, c'est normal ? Il ne faudrait pas plutôt `formatURL(body.url)` ici ?

2024-07-25 16:46 UTC, NemoDacremont commented on server/api/edit.post.ts
> +    if (isBodyWithProps(body, ['url'] as const) && typeof body.url === 'string') link.url = body.url
Sinon ça m'a l'air bien, je vais merge après cette correction

2024-07-25 17:08 UTC, NemoDacremont approved these changes

2024-07-25 17:08 UTC, merged